title: Rehydrator
tagline: Pattern-based content transformation for WordPress block migrations.
description: A PHP library for building migration scripts that populate block patterns with content during WordPress site migrations.
author: Human Made
baseurl: '/rehydrator'
url: 'https://humanmade.github.io'

theme: just-the-hm-docs

plugins:
  - jekyll-include-cache

aux_links:
  "Rehydrator on GitHub":
    - https://github.com/humanmade/rehydrator

nav_external_links:
  - title: GitHub source
    url: https://github.com/humanmade/rehydrator
  - title: Issues
    url: https://github.com/humanmade/rehydrator/issues
